#!/bin/bash
source /usr/lib/openfoam/openfoam2412/etc/bashrc
cd "$(dirname "$BASH_SOURCE")" || exit 1

echo "$(date +'%F %T') Cleaning old simulation data..."
rm -f log.*
rm -rf processor*
rm -rf [1-9]*
rm -rf constant/polyMesh
rm -rf postProcessing

echo "$(date +'%F %T') Clean up complete."

echo "$(date +'%F %T') Current directory: $PWD"

# cd ../../  # back to case root

# Run OpenFOAM pre-processing and solver steps
echo "$(date +'%F %T') Starting OpenFOAM pipeline..."

echo "$(date +'%F %T') Running surfaceFeatureExtract..."
surfaceFeatureExtract > log.surfaceFeatureExtract 2>&1
echo "$(date +'%F %T') Finished surfaceFeatureExtract"

echo "$(date +'%F %T') Running blockMesh..."
blockMesh > log.blockMesh 2>&1
echo "$(date +'%F %T') Finished blockMesh"

echo "$(date +'%F %T') Running decomposePar..."
decomposePar > log.decomposePar 2>&1
echo "$(date +'%F %T') Finished decomposePar"

# Run snappyHexMesh in parallel
NPROCS=$(foamDictionary system/decomposeParDict -entry numberOfSubdomains | awk '{gsub(/;/, "", $2); print $2}')
echo "$(date +'%F %T') Running snappyHexMesh on $NPROCS MPI processes..."
mpirun -np $NPROCS snappyHexMesh -parallel -overwrite > log.snappyHexMesh 2>&1
echo "$(date +'%F %T') Finished snappyHexMesh"

# Reconstruct mesh and update polyMesh
echo "$(date +'%F %T') Running reconstructParMesh..."
reconstructParMesh -mergeTol 1E-06 -noZero > log.reconstructParMesh 2>&1
echo "$(date +'%F %T') Finished reconstructParMesh"

rm -rf processor*

echo "$(date +'%F %T') Running final decomposePar..."
decomposePar > log.decomposePar 2>&1
echo "$(date +'%F %T') Finished final decomposePar"

echo "$(date +'%F %T') Running simpleFoam..."
mpirun -np $NPROCS simpleFoam -parallel > log.simpleFoam 2>&1
echo "$(date +'%F %T') Finished simpleFoam"

echo "$(date +'%F %T') Reconstructing final solution..."
reconstructPar -latestTime > log.reconstructPar 2>&1
echo "$(date +'%F %T') Reconstruction complete"

rm -rf processor*

# Final output check
VAR="$PWD/$(foamListTimes -latestTime)/U"
if [ -e "$VAR" ]; then
    echo "$(date +'%F %T') Finished successfully"
else
    echo "$(date +'%F %T') Simulation did not produce expected output"
    exit 1
fi