#!/bin/bash

value2=$PWD
path_to_file="$value2/log.simpleFoam"

gnuplot <<- EOF
    set terminal png size 800, 600
    set output 'residual_plot.png'
    set logscale y
    set title "Residuals of steady Laminar 60LPM for p5t1"
    set ylabel 'Residual'
    set xlabel 'No of Timesteps'
    set key outside

    plot "< cat '$path_to_file' | grep 'Solving for Ux' | cut -d' ' -f9 | tr -d ','" title 'Ux' with lines,\
    "< cat '$path_to_file' | grep 'Solving for Uy' | cut -d' ' -f9 | tr -d ','" title 'Uy' with lines,\
    "< cat '$path_to_file' | grep 'Solving for Uz' | cut -d' ' -f9 | tr -d ','" title 'Uz' with lines,\
    "< cat '$path_to_file' | grep 'Solving for p' | cut -d' ' -f9 | tr -d ','" title 'p' with lines
    set out
    #pause 1
    #reread
EOF
