#!/bin/sh
source /opt/openfoam/OpenFOAM-v2306/etc/bashrc
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication decomposePar
runParallel snappyHexMesh
# mpirun -np 2 snappyHexMesh -parallel >log.snappy
runApplication reconstructParMesh -latestTime -mergeTol 1E-06 -noZero
latest=$(foamListTimes -latestTime)
cp -r "$latest/polyMesh" constant/
rm -rf "$latest"
rm -rf processor*
rm log.decomposePar
#runApplication checkMesh –latestTime
runApplication decomposePar
runParallel $(getApplication)
# mpirun -np 2 simpleFoam -parallel >log.solver
runApplication reconstructPar -latestTime
rm -rf processor*
value2=$PWD
VAR="$value2/1000/U"
if [ -e "$VAR" ]
        then
                echo "Finished"
        else
                echo "doesn't exist!"
fi
#------------------------------------------------------------------------------
